package rules

import (
	trules "github.com/khulnasoft-lab/vul-policies/pkg/rules"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/accessanalyzer"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/apigateway"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/athena"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/cloudfront"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/cloudtrail"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/cloudwatch"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/codebuild"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/config"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/documentdb"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/dynamodb"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/ec2"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/ecr"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/ecs"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/efs"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/eks"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/elasticache"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/elasticsearch"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/elb"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/emr"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/iam"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/kinesis"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/kms"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/lambda"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/mq"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/msk"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/neptune"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/rds"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/redshift"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/s3"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/sam"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/sns"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/sqs"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/ssm"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/aws/workspaces"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/appservice"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/authorization"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/compute"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/container"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/database"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/datafactory"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/datalake"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/keyvault"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/monitor"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/network"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/securitycenter"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/storage"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/azure/synapse"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/cloudstack/compute"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/digitalocean/compute"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/digitalocean/spaces"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/github/actions"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/github/branch_protections"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/github/repositories"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/google/bigquery"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/google/compute"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/google/dns"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/google/gke"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/google/iam"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/google/kms"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/google/sql"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/google/storage"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/nifcloud/computing"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/nifcloud/dns"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/nifcloud/nas"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/nifcloud/network"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/nifcloud/rdb"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/nifcloud/sslcertificate"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/openstack/compute"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/openstack/networking"
	_ "github.com/khulnasoft-lab/vul-policies/rules/cloud/policies/oracle/compute"
	_ "github.com/khulnasoft-lab/vul-policies/rules/kubernetes/network"
)

func init() {
	for _, r := range trules.GetRules() {
		Register(r)
	}
}
